//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientPrZad3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name A from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMatrix", ReplyAction="*")]
        ClientPrZad3.ServiceReference1.SendMatrixResponse SendMatrix(ClientPrZad3.ServiceReference1.SendMatrixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMatrix", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.SendMatrixResponse> SendMatrixAsync(ClientPrZad3.ServiceReference1.SendMatrixRequest request);
        
        // CODEGEN: Generating message contract since element name idA from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultipleMatrix", ReplyAction="*")]
        ClientPrZad3.ServiceReference1.MultipleMatrixResponse MultipleMatrix(ClientPrZad3.ServiceReference1.MultipleMatrixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultipleMatrix", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.MultipleMatrixResponse> MultipleMatrixAsync(ClientPrZad3.ServiceReference1.MultipleMatrixRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatrix", ReplyAction="*")]
        ClientPrZad3.ServiceReference1.GetMatrixResponse GetMatrix(ClientPrZad3.ServiceReference1.GetMatrixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatrix", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMatrixResponse> GetMatrixAsync(ClientPrZad3.ServiceReference1.GetMatrixRequest request);
        
        // CODEGEN: Generating message contract since element name coloring from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateMandelbrot", ReplyAction="*")]
        ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse GenerateMandelbrot(ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateMandelbrot", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse> GenerateMandelbrotAsync(ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMandelbrot", ReplyAction="*")]
        ClientPrZad3.ServiceReference1.GetMandelbrotResponse GetMandelbrot(ClientPrZad3.ServiceReference1.GetMandelbrotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMandelbrot", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMandelbrotResponse> GetMandelbrotAsync(ClientPrZad3.ServiceReference1.GetMandelbrotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMatrixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMatrix", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.SendMatrixRequestBody Body;
        
        public SendMatrixRequest() {
        }
        
        public SendMatrixRequest(ClientPrZad3.ServiceReference1.SendMatrixRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMatrixRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string A;
        
        public SendMatrixRequestBody() {
        }
        
        public SendMatrixRequestBody(string A) {
            this.A = A;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMatrixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMatrixResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.SendMatrixResponseBody Body;
        
        public SendMatrixResponse() {
        }
        
        public SendMatrixResponse(ClientPrZad3.ServiceReference1.SendMatrixResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMatrixResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMatrixResult;
        
        public SendMatrixResponseBody() {
        }
        
        public SendMatrixResponseBody(string SendMatrixResult) {
            this.SendMatrixResult = SendMatrixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultipleMatrixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultipleMatrix", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.MultipleMatrixRequestBody Body;
        
        public MultipleMatrixRequest() {
        }
        
        public MultipleMatrixRequest(ClientPrZad3.ServiceReference1.MultipleMatrixRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultipleMatrixRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idB;
        
        public MultipleMatrixRequestBody() {
        }
        
        public MultipleMatrixRequestBody(string idA, string idB) {
            this.idA = idA;
            this.idB = idB;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultipleMatrixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultipleMatrixResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.MultipleMatrixResponseBody Body;
        
        public MultipleMatrixResponse() {
        }
        
        public MultipleMatrixResponse(ClientPrZad3.ServiceReference1.MultipleMatrixResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultipleMatrixResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MultipleMatrixResult;
        
        public MultipleMatrixResponseBody() {
        }
        
        public MultipleMatrixResponseBody(string MultipleMatrixResult) {
            this.MultipleMatrixResult = MultipleMatrixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatrixRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatrix", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GetMatrixRequestBody Body;
        
        public GetMatrixRequest() {
        }
        
        public GetMatrixRequest(ClientPrZad3.ServiceReference1.GetMatrixRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatrixRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetMatrixRequestBody() {
        }
        
        public GetMatrixRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMatrixResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMatrixResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GetMatrixResponseBody Body;
        
        public GetMatrixResponse() {
        }
        
        public GetMatrixResponse(ClientPrZad3.ServiceReference1.GetMatrixResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMatrixResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMatrixResult;
        
        public GetMatrixResponseBody() {
        }
        
        public GetMatrixResponseBody(byte[] GetMatrixResult) {
            this.GetMatrixResult = GetMatrixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateMandelbrotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMandelbrot", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GenerateMandelbrotRequestBody Body;
        
        public GenerateMandelbrotRequest() {
        }
        
        public GenerateMandelbrotRequest(ClientPrZad3.ServiceReference1.GenerateMandelbrotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateMandelbrotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int height;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int numThreadsPar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string coloring;
        
        public GenerateMandelbrotRequestBody() {
        }
        
        public GenerateMandelbrotRequestBody(int width, int height, int numThreadsPar, string coloring) {
            this.width = width;
            this.height = height;
            this.numThreadsPar = numThreadsPar;
            this.coloring = coloring;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateMandelbrotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMandelbrotResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GenerateMandelbrotResponseBody Body;
        
        public GenerateMandelbrotResponse() {
        }
        
        public GenerateMandelbrotResponse(ClientPrZad3.ServiceReference1.GenerateMandelbrotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateMandelbrotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateMandelbrotResult;
        
        public GenerateMandelbrotResponseBody() {
        }
        
        public GenerateMandelbrotResponseBody(string GenerateMandelbrotResult) {
            this.GenerateMandelbrotResult = GenerateMandelbrotResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMandelbrotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMandelbrot", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GetMandelbrotRequestBody Body;
        
        public GetMandelbrotRequest() {
        }
        
        public GetMandelbrotRequest(ClientPrZad3.ServiceReference1.GetMandelbrotRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMandelbrotRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetMandelbrotRequestBody() {
        }
        
        public GetMandelbrotRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMandelbrotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMandelbrotResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientPrZad3.ServiceReference1.GetMandelbrotResponseBody Body;
        
        public GetMandelbrotResponse() {
        }
        
        public GetMandelbrotResponse(ClientPrZad3.ServiceReference1.GetMandelbrotResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMandelbrotResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] GetMandelbrotResult;
        
        public GetMandelbrotResponseBody() {
        }
        
        public GetMandelbrotResponseBody(byte[] GetMandelbrotResult) {
            this.GetMandelbrotResult = GetMandelbrotResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ClientPrZad3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ClientPrZad3.ServiceReference1.WebService1Soap>, ClientPrZad3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientPrZad3.ServiceReference1.SendMatrixResponse ClientPrZad3.ServiceReference1.WebService1Soap.SendMatrix(ClientPrZad3.ServiceReference1.SendMatrixRequest request) {
            return base.Channel.SendMatrix(request);
        }
        
        public string SendMatrix(string A) {
            ClientPrZad3.ServiceReference1.SendMatrixRequest inValue = new ClientPrZad3.ServiceReference1.SendMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.SendMatrixRequestBody();
            inValue.Body.A = A;
            ClientPrZad3.ServiceReference1.SendMatrixResponse retVal = ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).SendMatrix(inValue);
            return retVal.Body.SendMatrixResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.SendMatrixResponse> ClientPrZad3.ServiceReference1.WebService1Soap.SendMatrixAsync(ClientPrZad3.ServiceReference1.SendMatrixRequest request) {
            return base.Channel.SendMatrixAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.SendMatrixResponse> SendMatrixAsync(string A) {
            ClientPrZad3.ServiceReference1.SendMatrixRequest inValue = new ClientPrZad3.ServiceReference1.SendMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.SendMatrixRequestBody();
            inValue.Body.A = A;
            return ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).SendMatrixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientPrZad3.ServiceReference1.MultipleMatrixResponse ClientPrZad3.ServiceReference1.WebService1Soap.MultipleMatrix(ClientPrZad3.ServiceReference1.MultipleMatrixRequest request) {
            return base.Channel.MultipleMatrix(request);
        }
        
        public string MultipleMatrix(string idA, string idB) {
            ClientPrZad3.ServiceReference1.MultipleMatrixRequest inValue = new ClientPrZad3.ServiceReference1.MultipleMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.MultipleMatrixRequestBody();
            inValue.Body.idA = idA;
            inValue.Body.idB = idB;
            ClientPrZad3.ServiceReference1.MultipleMatrixResponse retVal = ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).MultipleMatrix(inValue);
            return retVal.Body.MultipleMatrixResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.MultipleMatrixResponse> ClientPrZad3.ServiceReference1.WebService1Soap.MultipleMatrixAsync(ClientPrZad3.ServiceReference1.MultipleMatrixRequest request) {
            return base.Channel.MultipleMatrixAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.MultipleMatrixResponse> MultipleMatrixAsync(string idA, string idB) {
            ClientPrZad3.ServiceReference1.MultipleMatrixRequest inValue = new ClientPrZad3.ServiceReference1.MultipleMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.MultipleMatrixRequestBody();
            inValue.Body.idA = idA;
            inValue.Body.idB = idB;
            return ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).MultipleMatrixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientPrZad3.ServiceReference1.GetMatrixResponse ClientPrZad3.ServiceReference1.WebService1Soap.GetMatrix(ClientPrZad3.ServiceReference1.GetMatrixRequest request) {
            return base.Channel.GetMatrix(request);
        }
        
        public byte[] GetMatrix(string id) {
            ClientPrZad3.ServiceReference1.GetMatrixRequest inValue = new ClientPrZad3.ServiceReference1.GetMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GetMatrixRequestBody();
            inValue.Body.id = id;
            ClientPrZad3.ServiceReference1.GetMatrixResponse retVal = ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GetMatrix(inValue);
            return retVal.Body.GetMatrixResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMatrixResponse> ClientPrZad3.ServiceReference1.WebService1Soap.GetMatrixAsync(ClientPrZad3.ServiceReference1.GetMatrixRequest request) {
            return base.Channel.GetMatrixAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMatrixResponse> GetMatrixAsync(string id) {
            ClientPrZad3.ServiceReference1.GetMatrixRequest inValue = new ClientPrZad3.ServiceReference1.GetMatrixRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GetMatrixRequestBody();
            inValue.Body.id = id;
            return ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GetMatrixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse ClientPrZad3.ServiceReference1.WebService1Soap.GenerateMandelbrot(ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest request) {
            return base.Channel.GenerateMandelbrot(request);
        }
        
        public string GenerateMandelbrot(int width, int height, int numThreadsPar, string coloring) {
            ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest inValue = new ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GenerateMandelbrotRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.numThreadsPar = numThreadsPar;
            inValue.Body.coloring = coloring;
            ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse retVal = ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GenerateMandelbrot(inValue);
            return retVal.Body.GenerateMandelbrotResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse> ClientPrZad3.ServiceReference1.WebService1Soap.GenerateMandelbrotAsync(ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest request) {
            return base.Channel.GenerateMandelbrotAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GenerateMandelbrotResponse> GenerateMandelbrotAsync(int width, int height, int numThreadsPar, string coloring) {
            ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest inValue = new ClientPrZad3.ServiceReference1.GenerateMandelbrotRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GenerateMandelbrotRequestBody();
            inValue.Body.width = width;
            inValue.Body.height = height;
            inValue.Body.numThreadsPar = numThreadsPar;
            inValue.Body.coloring = coloring;
            return ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GenerateMandelbrotAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientPrZad3.ServiceReference1.GetMandelbrotResponse ClientPrZad3.ServiceReference1.WebService1Soap.GetMandelbrot(ClientPrZad3.ServiceReference1.GetMandelbrotRequest request) {
            return base.Channel.GetMandelbrot(request);
        }
        
        public byte[] GetMandelbrot(string id) {
            ClientPrZad3.ServiceReference1.GetMandelbrotRequest inValue = new ClientPrZad3.ServiceReference1.GetMandelbrotRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GetMandelbrotRequestBody();
            inValue.Body.id = id;
            ClientPrZad3.ServiceReference1.GetMandelbrotResponse retVal = ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GetMandelbrot(inValue);
            return retVal.Body.GetMandelbrotResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMandelbrotResponse> ClientPrZad3.ServiceReference1.WebService1Soap.GetMandelbrotAsync(ClientPrZad3.ServiceReference1.GetMandelbrotRequest request) {
            return base.Channel.GetMandelbrotAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientPrZad3.ServiceReference1.GetMandelbrotResponse> GetMandelbrotAsync(string id) {
            ClientPrZad3.ServiceReference1.GetMandelbrotRequest inValue = new ClientPrZad3.ServiceReference1.GetMandelbrotRequest();
            inValue.Body = new ClientPrZad3.ServiceReference1.GetMandelbrotRequestBody();
            inValue.Body.id = id;
            return ((ClientPrZad3.ServiceReference1.WebService1Soap)(this)).GetMandelbrotAsync(inValue);
        }
    }
}
